// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © rhapsodyz

//@version=5
indicator(title="RSI with Boll %B on Chart", shorttitle="RSI %B onC", overlay=true, format=format.price, precision=2, timeframe="", timeframe_gaps=true)

rsiLength       = input.int(14, minval=1, title="RSI Length", group="RSI Settings")
rsiSource       = input.source(hlc3, "RSI Source", group="RSI Settings")
rsiMALength     = input.int(14, title="MA Length", group="Boll Settings")
rsiBollMult     = input.float(2.0, minval=0.001, maxval=50, title="Boll StdDev", group="Boll Settings")
showDivergence  = input.bool(false, title="Show Divergence", group="RSI Settings")

up = ta.rma(math.max(ta.change(rsiSource), 0), rsiLength)
down = ta.rma(-math.min(ta.change(rsiSource), 0), rsiLength)
rsi = down == 0 ? 50 : up == 0 ? -50 : 50 - (100 / (1 + up / down))
rsiMA = ta.sma(rsi, rsiMALength)

rsiDiv = (rsi - rsiMA) / (ta.stdev(rsi, rsiMALength) * rsiBollMult)

break_up = false
break_down = false

if rsiDiv[1] < -1 and rsi[1] <= -20
    break_down := true

if rsiDiv[1] > 1 and rsi[1] >= 20
    break_up := true

plotchar(break_up, 'RSI Bought Breakout', '▼', location.abovebar, #f23645)
plotchar(break_down, 'RSI Sold Breakout', '▲', location.belowbar, #089981)