//@version=5
indicator(shorttitle="Boll", title="Bollinger Bands", overlay=true, timeframe="", timeframe_gaps=true)
// Use 21 as the period length. Classic is 20.
// Use EMA as the moving average. Classic is SMA.
// Use hlc3 as the source price. Classic is Close.
length = input.int(21, minval=1)
mult = input.float(2.0, minval=0.001, maxval=50, title="StdDev")

basis = ta.ema(hlc3, length)
dev = mult * ta.stdev(hlc3, length)
upper = basis + dev
lower = basis - dev
offset = input.int(0, "Offset", minval = -500, maxval = 500)

plot(basis, "Basis", color=#FF6D00, offset = offset)
p1 = plot(upper, "Upper", color=#2962FF, offset = offset)
p2 = plot(lower, "Lower", color=#2962FF, offset = offset)
fill(p1, p2, title = "Background", color=color.rgb(33, 150, 243, 95))