// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © rhapsodyz

//@version=5
indicator(shorttitle="Boll", title="Bollinger Bands", overlay=false, timeframe="", timeframe_gaps=true)
// Use 21 as the period length. Classic is 20.
// Use EMA as the moving average. Classic is SMA.
// Use hlc3 as the source price. Classic is Close.
length = input.int(21, minval=1, title = "Boll Length", group = "Boll Settings")
mult = input.float(2.0, minval=0.001, maxval=50, title="StdDev", group = "Boll Settings")
src = input.source(hlc3, "Boll Source", group="Boll Settings")
slowLength = input.int(14, minval = 1, title = "EMA Slow Length", group = "EMA Settings")
fastLength = input.int(49, minval = 1, title = "EMA Fast Length", group = "EMA Settings")

basis = ta.ema(src, length)
dev = mult * ta.stdev(src, length)
upper = basis + dev
lower = basis - dev
offset = input.int(0, "Offset", minval = -500, maxval = 500)

devSlowEMA = ta.ema(dev, slowLength)
devFastEMA = ta.ema(dev, fastLength)

plot(dev, "Dev", color=#FF6D00, offset = offset)
p1 = plot(devSlowEMA, "DevSlow", color=#2962FF, offset = offset)
p2 = plot(devFastEMA, "DevFast", color=#2962FF, offset = offset)
//fill(p1, p2, title = "Background", color=color.rgb(33, 150, 243, 95))