// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © rhapsodyz

//@version=5
strategy("Strategy", overlay = true, pyramiding = 0, initial_capital = 100000, commission_type = strategy.commission.percent, commission_value = 0.04, slippage = 2)

// #######################
// === General Numbers ===
// #######################

// === Equity Usage ===
equityUsage = input(0.9, title="Equity Usage Percentage")
_qty = (strategy.equity * equityUsage) / close

// === Input A ===


// === Input B ===


// === Input C ===


// ##################
// === Indicators ===
// ##################

// === Indicator A ===


// === Indicator B ===


// === Indicator C ===


// ##################
// === Conditions ===
// ##################

// === Condition A ===


// === Condition B ===


// === Condition C ===


// #######################
// === Risk Management ===
// #######################

// === Stop-loss ===
stopLoss   = input(3, "Stop Loss")
var float stopLossPrice = na

// === Take-profit ===
takeProfit = input(30, "Take Profit")
var float takeProfitPrice = na

// #######################
// === Order Execution ===
// #######################

// === Execute long entry ===
if enterLong
    stopLossPrice   := close * (1 - stopLoss/100)
    takeProfitPrice := close * (1 + takeProfit/100)
    strategy.entry("Long", strategy.long, qty = _qty)
    strategy.exit("exit", "Long", stop = stopLossPrice, limit = takeProfitPrice)

// === Execute long exit ===
if exitLong
    strategy.close("Long", qty_percent=100)

// === Execute short entry ===
if enterShort
    stopLossPrice   := close * (1 + stopLoss/100)
    takeProfitPrice := close * (1 - takeProfit/100)
    strategy.entry("Short", strategy.short, qty = _qty)
    strategy.exit("Exit", "Short", stop = stopLossPrice, limit = takeProfitPrice)

// === Execute short exit ===
if exitShort
    strategy.close("Short", qty_percent = 100)