// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © rhapsodyz

//@version=5
indicator("TD Sequential Number", shorttitle="TD Num", overlay=false)

// Function to calculate TD Setup
tdSetup() =>
    var int setupCount = 0
    var int setupDirection = 0
    if close > close[4]
        if setupDirection != 1
            setupCount := 1
            setupDirection := 1
        else
            setupCount += 1
    else if close < close[4]
        if setupDirection != -1
            setupCount := -1
            setupDirection := -1
        else
            setupCount -= 1
    else
        setupCount := 0
    [setupCount, setupDirection]

// Calculating TD Setup and TD Countdown
[setup, direction] = tdSetup()

// Plotting
tdUpperBand = hline(9, "TD Upper Band", color=#787B86)
midLinePlot = plot(0, color = na, editable = false, display = display.none)
tdLowerBand = hline(-9, "TD Lower Band", color=#787B86)
tdPlot = plot(setup, title = "TD Setup", style = plot.style_columns, color = (setup > 0 ? (setup > 8 ? #26A69A : #B2DFDB) : (setup < -8 ? #FF5252 : #FFCDD2)))
fill(tdPlot, midLinePlot, 18, 9, top_color = color.new(color.green, 0), bottom_color = color.new(color.green, 100),  title = "Overbought Gradient Fill")
fill(tdPlot, midLinePlot, -9,  -18,  top_color = color.new(color.red, 100), bottom_color = color.new(color.red, 0),      title = "Oversold Gradient Fill")
