// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © rhapsodyz

//@version=5
indicator("TD Sequential OnChart", shorttitle="TD", overlay=true)

// Function to calculate TD Setup
tdSetup() =>
    var int setupCount = 0
    var int setupDirection = 0
    if close > close[4]
        if setupDirection != 1
            setupCount := 1
            setupDirection := 1
        else
            setupCount += 1
    else if close < close[4]
        if setupDirection != -1
            setupCount := -1
            setupDirection := -1
        else
            setupCount -= 1
    else
        setupCount := 0
    [setupCount, setupDirection]

// Calculating TD Setup and TD Countdown
[setup, direction] = tdSetup()

// Plotting
tdPlot = plot(setup, color = na, editable = false, display = display.status_line)
plotshape(series=setup == 9, title = "TD9跌", location=location.abovebar, color=color.rgb(241, 222, 15), style=shape.labeldown, text="9▼", textcolor = color.black, display = display.pane)
plotshape(series=setup == -9, title = "TD9涨", location=location.belowbar, color=color.rgb(145, 222, 106), style=shape.labelup, text="9▲", textcolor = color.black, display = display.pane)
plotshape(series=setup == 13, title = "TD13跌", location=location.abovebar, color=color.rgb(237, 65, 43), style=shape.labeldown, text="13▼", textcolor = color.black, display = display.pane)
plotshape(series=setup == -13, title = "TD13涨", location=location.belowbar, color=color.rgb(28, 201, 51), style=shape.labelup, text="13▲", textcolor = color.black, display = display.pane)
