// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © rhapsodyz

//@version=5
indicator(title="Bollinger Bands", shorttitle="Boll", overlay=true, timeframe="", timeframe_gaps=true)

// ##################
// === Parameters ===
// ##################

// Use 21 as the period length. Classic is 20.
// Use EMA as the moving average. Classic is SMA.
// Use hlc3 as the source price. Classic is Close.

length = input.int(21, minval=1, title = "Boll Length", group = "Boll Settings")
mult = input.float(2.0, minval=0.001, maxval=50, title="StdDev", group = "Boll Settings")
src = input.source(hlc3, "Boll Source", group="Boll Settings")
offset = input.int(0, "Offset", minval = -500, maxval = 500)

// ##################
// === Indicators ===
// ##################

basis = ta.ema(src, length)
dev = mult * ta.stdev(src, length)
upper = basis + dev
lower = basis - dev
bbr = (src - lower)/(upper - lower)

// #############
// === Plots ===
// #############

bbrPlot = plot(bbr, color = color.green, editable = false, display = display.status_line)
plot(basis, "Basis", color=#FF6D00, offset = offset)
p1 = plot(upper, "Upper", color=#2962FF, offset = offset)
p2 = plot(lower, "Lower", color=#2962FF, offset = offset)
fill(p1, p2, title = "Background", color=color.rgb(33, 150, 243, 95))
