// This work is licensed under a Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0) https://creativecommons.org/licenses/by-nc-sa/4.0/
// © rhapsodyz

//@version=5
indicator(title     = "Indicator", 
     shorttitle     = "Ind", 
     overlay        = true, 
     format         = format.inherit,
     precision      = 2,
     timeframe      = timeframe.period, 
     timeframe_gaps = true)

// ##################
// === Parameters ===
// ##################



// ##################
// === Indicators ===
// ##################



// ##############
// === Alerts ===
// ##############



// #############
// === Plots ===
// #############
