// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © rhapsodyz

//@version=5
indicator(title     = "Bollinger Bands", 
     shorttitle     = "Boll", 
     overlay        = true, 
     format         = format.inherit,
     precision      = 2,
     timeframe      = timeframe.period, 
     timeframe_gaps = true)

// ##################
// === Parameters ===
// ##################


// ##################
// === Indicators ===
// ##################


// #############
// === Plots ===
// #############
