// This work is licensed under a Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0) https://creativecommons.org/licenses/by-nc-sa/4.0/
// © rhapsodyz

//@version=5
indicator(title     = "[Z] Neural Network Sub 42 - Volume - CMF", 
     shorttitle     = "N_CMF", 
     overlay        = false, 
     format         = format.inherit,
     precision      = 2)

//Chaikin Money Flow////////////////////////////////////////////////////////////
length19 = 50
ad19 = close==high and close==low or high==low ? 0 : ((2*close-low-high)/(high-low))*volume
cmf = math.sum(ad19, length19) / math.sum(volume, length19)
//plot(cmf, color=#43A047, title="MF")
//hline(0, color=#787B86, title="Zero", linestyle=hline.style_dashed)

//Chaikin Money Flow Signals
cmfcrossimportance = input.int(defval=3, minval=0, maxval=100, title="CMF Cross 50-Line Importance")
cmfcrossup = cmf > 0 and cmf[1] < 0 ? cmfcrossimportance : 0
cmfcrossupstatus = cmfcrossup != 0 ? "CMF Crossed 50-Line Up" : na
cmfcrossdown = cmf < 0 and cmf[1] > 0 ? cmfcrossimportance : 0
cmfcrossdownstatus = cmfcrossdown != 0 ? "CMF Crossed 50-Line Down" : na

cmflevimportance = input.int(defval=0, minval=0, maxval=100, title="CMF Level Importance")
cmflevup = cmf > 0 ? cmflevimportance : 0
cmflevupstatus = cmflevup != 0 ? "CMF Level Up" : na
cmflevdown = cmf < 0 ? cmflevimportance : 0
cmflevdownstatus = cmflevdown != 0 ? "CMF Level Down" : na